Fixed buggs and some adjustments
UrosLITS/UrosLITS pull request #10
Opened 2024-09-27 09:14 UTC by UrosLITS

Minor bug fixes and some adjustments inside the code.

2024-09-27 09:26 UTC, petarLits requested changes

2024-09-27 09:26 UTC, petarLits commented on lib/l10n/app_en.arb
> +  "error_auth": "Incorrect email or  password",
what is with translation?

2024-09-27 10:46 UTC, milicaLits approved these changes

2024-09-27 12:00 UTC, petarLits requested changes

2024-09-27 12:00 UTC, petarLits commented on lib/l10n/app_sr.arb
> +  "error_auth": "Neispravan email ili password",
passsword is not serbian word

2024-09-27 12:11 UTC, milicaLits approved these changes

2024-10-02 11:32 UTC, milicaLits requested changes

2024-10-02 11:32 UTC, milicaLits commented on lib/data/firebase_cloud_messaging.dart
> +        await rootBundle.loadString('assets/book-d21ec-c64560991d06.json');
use constant

2024-10-02 11:32 UTC, milicaLits commented on lib/presentation/bookPages/bloc/book_bloc.dart
> +        doNotPopDialog: true));
remove this

2024-10-02 11:32 UTC, milicaLits commented on lib/presentation/bookPages/bloc/book_bloc.dart
> +        doNotPopDialog: true));
ditto

2024-10-02 11:32 UTC, milicaLits commented on lib/data/firebase_auth/firebase_auth_singleton.dart
>        throw Exception(timeoutErrorMessage);
throw custom Exception class

2024-10-02 11:35 UTC, petarLits requested changes

2024-10-02 11:35 UTC, petarLits commented on lib/data/firebase_cloud_messaging.dart
>      print('Notification Sending Error Response status: ${response.statusCode}');
do we need this?

2024-10-04 09:22 UTC, petarLits approved these changes

2024-10-04 11:10 UTC, milicaLits approved these changes

2024-10-04 11:15 UTC, merged