BookPageView UI and started bloc
UrosLITS/UrosLITS pull request #5
Opened 2024-09-05 12:08 UTC by UrosLITS

Added necessary elements and created simple UI for now as well as 2 events for bloc for navigating through pages.Add,edit,delete yet to be created....

2024-09-05 12:55 UTC, petarLits requested changes

2024-09-05 12:55 UTC, petarLits commented on lib/presentation/common/custom_dialog.dart
> +      content: SingleChildScrollView(
do we need SingleChildScrollView here?

2024-09-05 13:13 UTC, milicaLits requested changes

2024-09-05 13:13 UTC, milicaLits commented on lib/data/firebase_firestore/firebase_db_manager.dart
> +      throw Exception("Cant reach server");
Replace with constant timeoutErrorMessage

2024-09-05 13:13 UTC, milicaLits commented on lib/presentation/bookPages/bloc/book_page_bloc.dart
> +    emit(NextPage(currentIndex: event.currentIndex + 1));
You don't have to forward current index through events and state for next and previous page, you can do the calculation in listener of BlocConsumer.

2024-09-06 07:02 UTC, lecicdjuro requested changes

2024-09-06 07:02 UTC, lecicdjuro commented on lib/presentation/bookPages/widgets/build_page_body.dart
> +            child: Text(""),
why empty text?

2024-09-06 07:02 UTC, lecicdjuro commented on lib/presentation/common/custom_dialog.dart
> +                  onPressed: positiveAnswer,
just do Navgaitor.pop(true)

2024-09-06 07:02 UTC, lecicdjuro commented on lib/presentation/common/custom_dialog.dart
> +                  onPressed: negativeAnswer,
just do Navgaitor.pop(false)

2024-09-06 07:02 UTC, lecicdjuro commented on lib/presentation/common/custom_dialog.dart
> +                  onPressed: negativeAnswer,
I understand that you use on it when you are developing Android, but this is bad practice for Flutter widgets

2024-09-06 08:54 UTC, lecicdjuro requested changes

2024-09-06 08:54 UTC, lecicdjuro commented on lib/presentation/book/view/home_page_view.dart
> +                  FirebaseAuthSingleton.instance.auth.signOut();
what if this async call fails?

2024-09-06 08:54 UTC, lecicdjuro commented on lib/presentation/book/view/home_page_view.dart
> +                  FirebaseAuthSingleton.instance.auth.signOut();
make event

2024-09-06 09:35 UTC, lecicdjuro approved these changes

2024-09-06 09:35 UTC, merged